AllCops:
  Exclude:
    - db/migrate/*
    - db/schema.rb
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  TargetRubyVersion: 2.4
  TargetRailsVersion: 5.1

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

Metrics/LineLength:
  Max: 120

Lint/ScriptPermission:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
