require:
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  Exclude:
    - db/migrate/*
    - db/schema.rb
    - vendor/**/*
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  NewCops: enable
  TargetRailsVersion: 7.1

Layout/LineLength:
  Max: 120

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Naming/VariableNumber:
  EnforcedStyle: snake_case

Lint/ScriptPermission:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

Style/Documentation:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/ExponentialNotation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/MixinUsage:
  Enabled: false