AllCops:
  Exclude:
    - db/migrate/*
    - db/schema.rb
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  TargetRubyVersion: 2.4
  TargetRailsVersion: 5.1

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'shared_examples']

Metrics/LineLength:
  Max: 120

Layout/EndOfLine:
  EnforcedStyle: crlf
  
Lint/ScriptPermission:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

Style/Documentation:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MixinUsage:
  Enabled: false
