FROM ruby:2.6.6-alpine

ENV LANG="C.UTF-8"
ENV PACKAGES bash bash-completion bash-doc build-base curl-dev sqlite sqlite-dev sqlite-libs vim zlib-dev

WORKDIR /app

RUN apk update \
 && apk upgrade \
 && apk add --no-cache $PACKAGES \
 && gem update --system \
 && gem update \
 && gem cleanup \
 && rm -rf /usr/lib/ruby/gems/*/cache/* \
 && printf "export PS1='ruby-${RUBY_VERSION}:\W \$ '\nalias l='ls -CF'\nalias la='ls -A'\nalias ll='ls -alF'\nalias ls='ls --color=auto'" > ~/.bashrc

CMD ["bash"]
