name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.5
    - name: Install Sqlite3
      run: |
        sudo apt-get install sqlite3 libsqlite3-dev
    - name: Build and test with Rake
      run: |
        gem update --system
        gem update
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rails db:migrate RAILS_ENV=test
        bundle exec rake
