name: CI Pipeline

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Install ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4.4
        bundler-cache: true

    - name: Install sqlite3
      run: |
        sudo apt-get install sqlite3 libsqlite3-dev

    - name: Install gem dependencies
      run: |
        bundle check || bundle install

    - name: Run Rubocop
      run: |
        bundle exec rake rubocop

    - name: Run RSpec
      run: |
        bundle exec rails db:migrate RAILS_ENV=test
        bundle exec rake spec

  publish:
    name: Publish
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Retrieve application version
      id: app-version
      run: echo "::set-output name=version::$(cat config/initializers/version.rb  | grep VERSION | awk -F"'" '{print$2}')"

    - name: Create GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.app-version.outputs.version }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build & push Docker image
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: kakuzei/api.kakuzei.com
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,${{ steps.app-version.outputs.version }}"
